### ISSUE TITLE
Index of programs being used for testing

### ISSUE THREAD

**Issue by nforbus** [connorkuehl/llvm-project#14]
When testing randstruct with a specific program, please comment here with the details of the program, how you tested it, what program it was (repo included), and what the results were.

**Comment by tim-pugh** [comment]
https://github.com/neovim/neovim

Think I'll give this a shot at attempting to build.

**Comment by tim-pugh** [comment]
Building Inkscape on Windows with Clang
Instructions provided here: http://wiki.inkscape.org/wiki/index.php/Compiling_Inkscape_on_Windows_with_MSYS2

I'll need to edit the "ninja" file which I'm working towards.

Repo:
git clone --recurse-submodules https://gitlab.com/inkscape/inkscape.git master
